name: Build and Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build -t sanjanafernandosandamini/forex-leverage-app:latest .

    - name: Push the Docker image
      run: |
        docker push yourdockerhubusername/forex-leverage-app:latest
